'use strict';

var npmDest = 'dist';
var buildDest = 'dist';
var entryJS = 'src/js/app.js';
var devDir = 'dev/';
var tmpDir = '.tmp/';
var jsBundle = 'fittable.js';
var cssBundle = 'fittable.css';

module.exports = function (grunt) {
  // Project configuration
  grunt.initConfig({

    pkg: grunt.file.readJSON('package.json'),

    concurrent: {
      options: {
        logConcurrentOutput: true
      },
      dev: {
        tasks: [
          'compass:dev',              // start compass watch
          'browserify:dev',           // start watchify
          'copy:dev',                 // copy HTML files
          'watch:copyDev',            // watch src files
          'watch:autoprefixerDev',    // watch for CSS generated by Compass
          'browserSync',              // start static files server
        ],
        options: {
          logConcurrentOutput: true,
          limit: Infinity
        },
      },
      devNpm: {
        tasks: [
          'compass:dev',
          'watch:copyDev',
          'watch:autoprefixerDev',
          'watch:npm'
        ]
      },
      dist: {
        tasks: [
          'css:dist',
          'browserify:dist',
          'browserify:min',
          'copy:dist',
        ]
      },
      npm: {
        tasks: [
          'babel:npm',
          'copy:npm'
        ]
      }
    },

    // Empties folders to start fresh
    clean: {
      dist: {
        files: [{
          dot: true,
          src: [
            tmpDir,
            'dist/*',
            '!dist/.git*'
          ]
        }]
      },
      dev: {
        files: [{
          dot: true,
          src: [
            devDir,
            tmpDir
          ]
        }]
      }
    },

    // Compiles Sass to CSS and generates necessary files if requested
    // autoprefixer is invoked from compass, see config.rb
    compass: {
      dev: {
        options: {
          sassDir: 'src/scss',
          cssDir: tmpDir,
          noLineComments: true,
          sourcemap: true,
          watch: true,
          force: true
        }
      },
      dist: {
        options: {
          sassDir: 'src/scss',
          cssDir: buildDest,
          environment: 'production'
        }
      }
    },

    // Watches files for changes and runs tasks based on the changed files
    watch: {
      'copyDev': {
        files: ['src/*.html'],
        tasks: ['copy:dev']
      },
      'autoprefixerDev': {
        files: [tmpDir + '**/*.css'],
        tasks: ['autoprefixer:dev'],
        options: {
          verbose: true
        },
      },
      npm: {
        files: ['src/js/**/*.js'],
        tasks: ['babel:npm']
      }
    },

    autoprefixer: {
      dev: {
        options: {
          map: true
        },
        files: [{
          src: [tmpDir + cssBundle],
          dest: devDir + cssBundle
        }]
      },
      dist: {
        files: [{
          src: 'dist/*.css'
        }]
      }
    },

    // Copies remaining files to places other tasks can use
    copy: {
      dist: {
        files: [{
          expand: true,
          cwd: 'src/',
          dest: buildDest,
          flatten: false,
          src: [
            'index.html',
            'landing.html',
            'img/**',
          ]
        }]
      },
      npm: {
        files: [{
          expand: true,
          dest: npmDest,
          cwd: './src',
          src: [
            'lang/*'
          ]
        }]
      },
      dev: {
        files: [{
          expand: true,
          cwd: 'src/',
          dest: devDir,
          flatten: false,
          src: [
            'index.html',
            'landing.html',
            'img/**',
          ]
        }]
      },
    },

    // Browserify
    browserify: {
      options: {
        transform: [ 'babelify' ],
        browserifyOptions: {
          debug: true,
          standalone: 'fittable'
        }
      },
      dev: {
        src: entryJS,
        dest: devDir + jsBundle,
        options: {
          watch: true,
          keepAlive: true,
          transform: [[{}, 'babelify']],
          browserifyOptions: {
            debug: true,
            standalone: 'fittable'
          }
        }
      },
      dist: {
        files: {
          'dist/fittable.js': entryJS
        }
      },
      min: {
        options: {
          transform: [ 'babelify' ],
          plugin: [ 'minifyify' ]
        },
        files: {
          'dist/fittable.min.js': entryJS
        }
      }
    },

    // Babel: Used for npm prepublishing, otherwise see browserify
    babel: {
      options: {
        sourceMap: true
      },
      npm: {
        files: [{
            expand: true,
            cwd: 'src/js',
            src: ['**/*.js'],
            dest: npmDest + '/js'
        }]
      }
    },

    // browserSync: Provides static server and assets reloading
    browserSync: {
      bsFiles: {
          src: [
            devDir + '*.css',
            devDir + '*.html',
            devDir + '*.js'
          ]
      },
      options: {
        server: {
          baseDir: devDir
        },
        open: false
      }
    },

  });

  // Load grunt tasks automatically
  require('load-grunt-tasks')(grunt);

  grunt.registerTask('touchCSS', 'Creates an empty CSS file for watching', function() {
    grunt.file.write(tmpDir + cssBundle);
  });

  grunt.registerTask('dev', [
    'touchCSS',
    'concurrent:dev',
  ]);

  grunt.registerTask('devNpm', [
    'touchCSS',
    'copy:dev',
    'copy:npm',
    'concurrent:devNpm',
  ]);

  grunt.registerTask('css:dist', [
    'compass:dist',
    'autoprefixer:dist'
  ]);

  grunt.registerTask('build', [
    'clean:dist',
    'concurrent:dist',
  ]);

  grunt.registerTask('build:npm', [
    'build',
    'concurrent:npm'
  ]);

  grunt.registerTask('default', ['dev']);
};
