
export const SETTINGS_CHANGE = 'SETTINGS_CHANGE'
export const VIEW_DATE_CHANGE = 'VIEW_DATE_CHANGE'
export const VIEW_FILTER_CHANGE = 'VIEW_FILTER_CHANGE'
export const EVENTS_REQUEST = 'EVENTS_REQUEST'
export const EVENTS_RESPONSE = 'EVENTS_RESPONSE'
