#!/usr/bin/env node
require('shelljs/global')

var baseDir = 'src'
var targetDir = 'dist'

var files = [
  baseDir + '/index.html',
  baseDir + '/landing.html',
  baseDir + '/signpost.html',
  baseDir + '/images',
  baseDir + '/locales',
]

mkdir('-p', targetDir)
cp('-Rf', files, targetDir)
